# Generated by Django 6.0 on 2025-12-30 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non-Vegetarian'), ('Vegan', 'Vegan')], default='Non-Veg', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast', models.TextField()),
                ('lunch', models.TextField()),
                ('dinner', models.TextField()),
                ('snacks', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='api.userprofile')),
            ],
            options={
                'db_table': 'daily_diet_plans',
                'ordering': ['-date'],
                'unique_together': {('user_profile', 'date')},
            },
        ),
    ]
