# Generated by Django 6.0 on 2025-12-30 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_dietary_preference_dailydietplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_glasses', models.IntegerField(default=0, help_text='Number of 250ml glasses')),
                ('target_glasses', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='api.userprofile')),
            ],
            options={
                'db_table': 'water_logs',
                'unique_together': {('user_profile', 'date')},
            },
        ),
    ]
