# Generated by Django 6.0 on 2025-12-30 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_waterlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast_content', models.TextField(blank=True, help_text='What was eaten for breakfast')),
                ('breakfast_calories', models.FloatField(default=0)),
                ('lunch_content', models.TextField(blank=True, help_text='What was eaten for lunch')),
                ('lunch_calories', models.FloatField(default=0)),
                ('dinner_content', models.TextField(blank=True, help_text='What was eaten for dinner')),
                ('dinner_calories', models.FloatField(default=0)),
                ('snacks_content', models.TextField(blank=True, help_text='What was eaten for snacks')),
                ('snacks_calories', models.FloatField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meal_logs', to='api.userprofile')),
            ],
            options={
                'db_table': 'daily_meal_logs',
                'unique_together': {('user_profile', 'date')},
            },
        ),
    ]
