# Generated by Django 6.0 on 2025-12-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dailymeallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydietplan',
            name='breakfast_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailydietplan',
            name='dinner_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailydietplan',
            name='lunch_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailydietplan',
            name='snacks_calories',
            field=models.FloatField(default=0),
        ),
    ]
