# Generated by Django 6.0 on 2025-12-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dailydietplan_breakfast_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pro Plan', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monthly subscription fee', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro')], default='Free', max_length=20),
        ),
    ]
