# Generated by Django 5.0.2 on 2026-03-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diet_restrictions',
            field=models.TextField(blank=True, help_text='Comma-separated list (e.g., Gluten-Free, Keto, Halal)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_allergies',
            field=models.TextField(blank=True, help_text='Comma-separated list (e.g., Peanuts, Dairy, Shellfish)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Comma-separated list (e.g., Diabetes, Hypertension)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text="URL to user's profile image", max_length=500, null=True),
        ),
    ]
