# Generated by Django 5.0.2 on 2026-03-10 16:24

import django.db.models.deletion
from django.db import migrations, models


def _split_csv_names(raw_value):
    if not raw_value:
        return []
    names = []
    seen = set()
    for part in str(raw_value).split(','):
        name = part.strip()
        lowered = name.lower()
        if name and lowered not in seen:
            names.append(name)
            seen.add(lowered)
    return names


def migrate_normalized_data(apps, schema_editor):
    UserProfile = apps.get_model('api', 'UserProfile')
    FoodAllergy = apps.get_model('api', 'FoodAllergy')
    MedicalCondition = apps.get_model('api', 'MedicalCondition')
    DietRestriction = apps.get_model('api', 'DietRestriction')
    SubscriptionPlan = apps.get_model('api', 'SubscriptionPlan')
    Transaction = apps.get_model('api', 'Transaction')

    for profile in UserProfile.objects.all():
        allergies = []
        for name in _split_csv_names(getattr(profile, 'food_allergies', '')):
            allergy, _ = FoodAllergy.objects.get_or_create(name=name)
            allergies.append(allergy.id)
        if allergies:
            profile.food_allergy_items.set(allergies)

        conditions = []
        for name in _split_csv_names(getattr(profile, 'medical_conditions', '')):
            condition, _ = MedicalCondition.objects.get_or_create(name=name)
            conditions.append(condition.id)
        if conditions:
            profile.medical_condition_items.set(conditions)

        restrictions = []
        for name in _split_csv_names(getattr(profile, 'diet_restrictions', '')):
            restriction, _ = DietRestriction.objects.get_or_create(name=name)
            restrictions.append(restriction.id)
        if restrictions:
            profile.diet_restriction_items.set(restrictions)

    for transaction in Transaction.objects.exclude(plan_name=''):
        plan_name = getattr(transaction, 'plan_name', '').strip()
        if not plan_name:
            continue
        plan, _ = SubscriptionPlan.objects.get_or_create(
            name=plan_name,
            defaults={'amount': 0, 'description': 'Migrated from legacy transaction data.'},
        )
        transaction.plan_id = plan.id
        transaction.save(update_fields=['plan'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_diet_restrictions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'diet_restrictions',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'food_allergies',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'medical_conditions',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diet_restriction_items',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='api.dietrestriction'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='food_allergy_items',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='api.foodallergy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_condition_items',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='api.medicalcondition'),
        ),
        migrations.RunPython(migrate_normalized_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='transaction',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='diet_restrictions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='food_allergies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='medical_conditions',
        ),
    ]
